spring:
  application:
    name: genai-worker
  main:
    web-application-type: none
  elasticsearch:
    uris: ${SPRING_ELASTICSEARCH_URIS:http://elasticsearch:9200}
    username: ${SPRING_ELASTICSEARCH_USERNAME:elastic}
    password: ${SPRING_ELASTICSEARCH_PASSWORD:MyStrongPassword}

gemini:
  model: ${GEMINI_MODEL:gemini-1.5-flash-001}
  api-key: ${GEMINI_API_KEY:}
  endpoint: ${GEMINI_ENDPOINT:https://generativelanguage.googleapis.com/v1beta}
  temperature: ${GEMINI_TEMPERATURE:0.4}

worker:
  bootstrap-servers: ${BOOTSTRAP_SERVERS:localhost:9092}
  group-id: ${GROUP_ID:genai-workers}
  input-topic: ${INPUT_TOPIC:genai-queue}
  output-topic: ${OUTPUT_TOPIC:result}
  auto-offset-reset: ${AUTO_OFFSET_RESET:earliest}
  enable-auto-commit: ${ENABLE_AUTO_COMMIT:false}
  poll-ms: ${POLL_MS:1000}
